version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./:/go/src/app
    ports:
      - "3000:3000"
    links:
      - db
    env_file:
      - .env

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloud-track
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  db-data:
    driver: local