version: '3'
services:
  app:
    build: 
      context: .
    volumes:
      - ./:/go/src/app
    env_file:
      - .env
    tty: true
    ports:
      - "8080:8080"
    links:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloud-track
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  db-data:
    driver: local